language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

install: 
  - pip install .
  - pip install 'python-coveralls<2.6'

script: coverage run setup.py test

after_success:
  - coveralls
