language: python
dist: trusty

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: 3.8
      dist: xenial
    - python: nightly
    - python: pypy
  allow_failures:
    - python: nightly

script: python setup.py test
